[package]
name = "falkordb"
version = "0.1.1"
edition = "2021"
description = "A FalkorDB Rust client"
license = "SSPL-1.0"


[dependencies]
log = { version = "0.4.21", default-features = false, features = ["std"] }
parking_lot = { version = "0.12.3", default-features = false, features = ["deadlock_detection"] }
redis = { version = "0.25.4", default-features = false, optional = true, features = ["sentinel"] }
regex = { version = "1.10.4", default-features = false, features = ["std", "perf", "unicode-bool", "unicode-perl"] }
strum = { version = "0.26.2", default-features = false, features = ["std", "derive"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", default-features = false, features = ["macros", "sync", "rt-multi-thread"], optional = true }
tracing = { version = "0.1.40", default-features = false, features = ["std", "attributes"] }

[features]
default = ["redis", "tokio"]

redis = ["dep:redis"]
native-tls = ["redis/tls-native-tls"]
rustls = ["redis/tls-rustls"]

tokio = ["dep:tokio", "redis/tokio-comp"]
tokio-native-tls = ["tokio", "redis/tokio-native-tls-comp"]
tokio-rustls = ["tokio", "redis/tokio-rustls-comp"]


[[example]]
name = "basic_usage"
required-features = ["redis"]

[[example]]
name = "asynchronous"
required-features = ["redis", "tokio"]
