name: Linux Build + Tests

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - uses: taiki-e/install-action@nextest
      - name: Populate test graph
        run: pip install falkordb && ./resources/populate_graph.py
      - name: Test
        run: cargo nextest run --all
    services:
      falkordb:
        image: falkordb/falkordb:edge
        ports:
          - 6379:6379