name: Code Coverage

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: linux-latest

    services:
      falkordb:
        image: falkordb/falkordb:edge
        volumes:
          - resources/imdb.rdb:/FalkorDB/dump.rdb
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Generate Code Coverage
        run: cargo llvm-cov nextest --all --codecov --output-path codecov.json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true