name: Publish on crates.io

on:
  push:
    tags: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Ensure formatting
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Rustfmt
        run: cargo fmt --all --check

  # Make sure no unwanted licenses or yanked crates have slipped in
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1

  # Make sure the release's build works
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - uses: taiki-e/install-action@nextest
      - name: Populate test graph
        run: pip install falkordb && ./resources/populate_graph.py
      - name: Test
        run: cargo nextest run --all
    services:
      falkordb:
        image: falkordb/falkordb:edge
        ports:
          - 6379:6379

  # Ensure no clippy warnings
  check-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Clippy
        run: cargo clippy --all

  # Make sure the release's docs are full
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Doc
        run: cargo doc --all

  # Actually publish to crates.io
  crates-io:
    needs:
      - build-linux
      - doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cargo Release
        run: cargo install cargo-release
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Publish
        run: |-
          cargo release \
            publish \
            --all-features \
            --allow-branch HEAD \
            --no-confirm \
            --no-verify \
            --execute